export interface BoothDetail {
  region_name: string;
  history: string;
  features: string;
  official_site?: string;
  type?: "sake" | "shochu" | "awamori" | "beer" | "whisky" | "liqueur" | "food" | "service" | "other";
  tags?: string[];
  flavor?: "amaguchi" | "karaguchi" | "balance";
}

export interface BoothInfo {
  id: string;
  name: string;
  details?: BoothDetail;
}

const COMMON_SERVICE_DETAIL: BoothDetail = {
  region_name: "행사 인프라",
  history: "특정 양조장이 아니라, 수입사·유통사·행사 주최 측이 운영하는 안내 및 판매 거점입니다.",
  features: "여러 양조장의 술을 한자리에서 시음·비교하고, 마음에 드는 제품을 구매하거나 굿즈 및 정보를 얻을 수 있는 공식 창구입니다.",
  official_site: "",
  type: "service",
  tags: ["안내", "판매", "시음", "이벤트"]
};

export const FESTIVAL_BOOTHS: Record<string, BoothInfo[]> = {
  A: [
    { id: "A01", name: "(주)니혼슈코리아 안내부스", details: COMMON_SERVICE_DETAIL },
    { id: "A02", name: "(주)니혼슈코리아 판매부스", details: COMMON_SERVICE_DETAIL },
    { id: "A03", name: "고쿠류", details: { region_name: "후쿠이", history: "1804년 창업, 에이헤이지 인근 지하수를 사용한 전통 명가.", features: "지나치게 화려하지 않은 기품 있는 향과 실크처럼 매끄러운 목넘김.", official_site: "https://www.kokuryu.co.jp", type: "sake", tags: ["전통", "프리미엄"], flavor: "balance" } },
    { id: "A04", name: "데와자쿠라", details: { region_name: "야마가타", history: "1892년 창업, 긴조슈 대중화의 선구자.", features: "사과·멜론을 떠올리게 하는 화사한 과실 향과 깨끗한 피니시.", official_site: "https://www.dewazakura.co.jp", type: "sake", tags: ["긴조", "과실향"], flavor: "amaguchi" } },
    { id: "A05", name: "코시노칸바이", details: { region_name: "니가타", history: "니가타 탄레이 카라쿠치의 대명사.", features: "맑고 깨끗한 인상, 입안을 말끔하게 씻어주는 드라이한 식중주.", official_site: "https://www.koshinokanbai.co.jp", type: "sake", tags: ["드라이", "탄레이"], flavor: "karaguchi" } },
    { id: "A06", name: "야마시로야", details: { region_name: "니가타", history: "전통 키모토 제조법으로 빚은 사케.", features: "모든 술을 키모토 제법으로 빚어 산미와 감칠맛이 살아있음.", official_site: "https://sugihime.jp", type: "sake", tags: ["키모토", "산미"], flavor: "karaguchi" } },
    { id: "A07", name: "이네토아가베", details: { region_name: "아키타", history: "2021년 설립된 혁신적 크래프트 사케 양조장.", features: "쌀을 기본으로 아가베, 홉 등 다양한 재료를 활용한 실험적 스타일.", official_site: "https://inetoagave.com", type: "other", tags: ["크래프트", "혁신"], flavor: "balance" } },
    { id: "A08", name: "(주)니혼슈코리아 시음부스", details: COMMON_SERVICE_DETAIL },
    { id: "A09", name: "스이게이", details: { region_name: "고치", history: "고치 식문화에 어울리는 깔끔한 사케 제작.", features: "단맛은 절제하고 선명한 산미와 드라이한 피니시 강조.", official_site: "https://suigei.jp", type: "sake", tags: ["드라이", "식중주"], flavor: "karaguchi" } },
    { id: "A10", name: "치토세츠루 / 아즈마이치", details: { region_name: "홋카이도/사가", history: "홋카이도 최초의 양조장과 사가의 전통 명가의 만남.", features: "청량한 스타일과 묵직한 쌀맛의 대조가 특징.", official_site: "https://www.chitosetsuru.jp", type: "sake", tags: ["전통", "지역색"], flavor: "balance" } },
    { id: "A11", name: "하츠카메 / 이소지만", details: { region_name: "시즈오카", history: "시즈오카를 대표하는 고급 양조장.", features: "투명한 주질과 정교하고 화려한 향.", official_site: "", type: "sake", tags: ["프리미엄", "긴조"], flavor: "karaguchi" } },
    { id: "A12", name: "우고노츠키 / 우타시로", details: { region_name: "히로시마/후쿠이", history: "부드러운 주질로 유명한 히로시마와 후쿠이의 브랜드.", features: "부드럽고 투명한 주질이 공통적인 특징.", official_site: "", type: "sake", tags: ["부드러움", "섬세함"], flavor: "amaguchi" } },
    { id: "A13", name: "타이메이 / 카네하치", details: { region_name: "오이타", history: "보리 소주를 전문으로 다뤄온 전통 증류 명가.", features: "볶은 보리 특유의 고소하고 스모키한 향이 일품.", official_site: "", type: "shochu", tags: ["보리소주", "고소함"], flavor: "karaguchi" } },
  ],
  B: [
    { id: "B03", name: "이마니시/카모니시키/토요비진/센킨/오니비/사츠마시마비진/아오카게/고다이우메슈", details: { region_name: "혼합", history: "모던 사케와 명품 소주들의 집합.", features: "현대적 감각의 사케부터 진한 고구마 소주까지.", official_site: "", type: "other", tags: ["모던", "쇼츄"], flavor: "balance" } },
    { id: "B04", name: "아와모리잔파", details: { region_name: "오키나와", history: "아와모리 대중화의 상징.", features: "부드럽고 깔끔한 아와모리, 입문자도 즐기기 좋음.", official_site: "https://www.zanpa.co.jp", type: "awamori", flavor: "karaguchi" } },
    { id: "B05", name: "본", details: { region_name: "후쿠이", history: "장기 저온 숙성 전문 명가.", features: "빙온 숙성을 통한 농밀한 감칠맛과 중후함.", official_site: "https://www.born.co.jp", type: "sake", flavor: "balance" } },
    { id: "B06", name: "쿠마가이주류 판매부스", details: COMMON_SERVICE_DETAIL },
    { id: "B07", name: "SODAWARI (소다와리)", details: { region_name: "기획부스", history: "기존 소주·리큐르 문화를 ‘탄산과 섞어 마시는 스타일’로 재해석하는 콘셉트 부스입니다.", features: "소다와리 스타일 하이볼을 중심으로 청량감 있는 조합을 제안합니다.", official_site: "", type: "other", tags: ["하이볼", "청량감", "믹솔로지"] } },
    { id: "B08", name: "사케노이치자 (酒の一좌)", details: { region_name: "기획/유통", history: "후쿠오카 기반의 주류 기획 브랜드로, 여러 양조장과 협업해 다양한 술을 소개합니다.", features: "큐슈 지역의 숨은 명주와 개성 강한 소주·리큐르를 선별해 소개하는 편집숍 콘셉트입니다.", official_site: "", type: "other", tags: ["편집숍", "큐레이션", "큐슈"] } },
    { id: "B09", name: "미이노고토부키", details: { region_name: "후쿠오카", history: "슬램덩크 정대만 사케로 유명한 드라이 사케의 명가.", features: "깔끔하면서도 선명한 맛, 드라이한 설계가 특징.", official_site: "", type: "sake", flavor: "karaguchi" } },
    { id: "B10", name: "비죠후", details: { region_name: "고치", history: "고치 식문화와 함께 성장한 명가.", features: "산뜻한 산미와 가벼운 질감으로 해산물과 잘 어울림.", official_site: "", type: "sake", flavor: "karaguchi" } },
    { id: "B11", name: "사라 (SARA)", details: { region_name: "리큐르", history: "젊은 층을 타깃으로 한 디자인·맛 중심의 모던 브랜드입니다.", features: "달콤·산뜻한 풍미의 리큐르가 많으며, 칵테일 베이스로도 훌륭합니다.", official_site: "", type: "liqueur", tags: ["모던", "트렌디", "칵테일"] } },
    { id: "B12", name: "칸코바이", details: { region_name: "미에", history: "지역 밀착형 소규모 양조장.", features: "은은한 꽃향과 부드러운 단맛의 편안한 사케.", official_site: "", type: "sake", flavor: "amaguchi" } },
    { id: "B13", name: "지자케CY코리아(판매부스)", details: COMMON_SERVICE_DETAIL },
  ],
  D: [
    { id: "D01", name: "겐비시", details: { region_name: "효고", history: "1505년 창업한 초장수 양조장.", features: "묵직한 클래식 스타일, 데워 마셔도 훌륭한 전통파.", official_site: "https://www.kenbishi.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "D02", name: "치에비진", details: { region_name: "오이타", history: "부드러운 단맛의 사케와 리큐르로 인기.", features: "디저트 같은 부드러운 단맛과 산미의 균형.", official_site: "https://chiebijin.com", type: "sake", flavor: "amaguchi" } },
    { id: "D03", name: "쵸요후쿠무스메 (야마구치)", details: { region_name: "야마구치", history: "1919년 창업, 야마구치의 부드러운 연수를 사용한 전통 양조장입니다.", features: "쌀 본연의 포근한 단맛과 온화한 과실 향이 특징인 힐링 스타일입니다.", official_site: "", type: "sake", flavor: "amaguchi", tags: ["포근함", "단맛", "전통"] } },
    { id: "D04", name: "즈이요 (구마모토)", details: { region_name: "구마모토", history: "1867년 창업, 전통주 ‘아카자케(붉은 술)’ 생산으로도 유명합니다.", features: "묵직한 감칠맛과 두터운 풍미를 가진 전통 규슈 스타일입니다.", official_site: "", type: "sake", flavor: "karaguchi", tags: ["아카자케", "감칠맛", "묵직함"] } },
    { id: "D05", name: "에미시키센세이션", details: { region_name: "시가", history: "실험적인 '센세이션' 시리즈로 유명한 모던 명가.", features: "열대 과일 향과 개성적인 산미, 팝한 라벨이 특징.", official_site: "https://www.emishiki.com", type: "sake", flavor: "amaguchi" } },
    { id: "D06", name: "나츠리키 (夏力)", details: { region_name: "여름한정", history: "양조장에서 여름 시즌에 내는 기획 브랜드 라인업입니다.", features: "산미와 청량감을 강조해 차갑게 마셨을 때 가장 시원합니다.", official_site: "", type: "sake", flavor: "karaguchi", tags: ["나츠자케", "여름한정", "청량감"] } },
    { id: "D07", name: "니혼사케이벤트", details: COMMON_SERVICE_DETAIL },
    { id: "D08", name: "니혼사케판매부스", details: COMMON_SERVICE_DETAIL },
    { id: "D09", name: "니혼사케시음부스", details: COMMON_SERVICE_DETAIL },
  ],
  E: [
    { id: "E01", name: "닷사이", details: { region_name: "야마구치", history: "세계적인 프리미엄 사케 브랜드.", features: "화사한 과실 향과 실크 같은 질감의 준마이 다이긴조.", official_site: "https://dassai.com", type: "sake", flavor: "amaguchi" } },
    { id: "E02", name: "텡구마이", details: { region_name: "이시카와", history: "1823년 창업, 전통 야마하이 제법을 확립하며 전국적인 명성을 얻은 명가입니다.", features: "진한 감칠맛과 뚜렷한 산미가 공존하며, 중후한 요리와 잘 어울리는 깊은 맛이 특징입니다.", official_site: "https://www.tengumai.co.jp", type: "sake", tags: ["야마하이", "이시카와", "감칠맛"], flavor: "karaguchi" } },
    { id: "E03", name: "가모츠루", details: { region_name: "히로시마", history: "히로시마를 대표하는 금박 사케 명가.", features: "화사한 향과 부드러운 단맛의 전형적인 긴조 스타일.", official_site: "https://www.kamotsuru.jp", type: "sake", flavor: "amaguchi" } },
    { id: "E04", name: "코마사양조", details: { region_name: "가고시마", history: "1883년 설립, 고구마 소주 ‘호우잔’ 시리즈와 크래프트 진으로 유명한 증류주 명가입니다.", features: "전통의 단맛을 살리면서도 깔끔한 현대적 스타일의 소주와 섬세한 진을 생산합니다.", official_site: "https://www.komasa.jp", type: "shochu", tags: ["가고시마", "크래프트진", "위스키"], flavor: "balance" } },
    { id: "E05", name: "킹양조 (King Shuzo)", details: { region_name: "효고", history: "1900년 전후 설립, 미림과 알코올 음료 등 폭넓은 제품을 생산합니다.", features: "안정적인 품질의 가성비 사케 라인업을 공급하는 대형 메이커입니다.", official_site: "", type: "sake", flavor: "balance", tags: ["대형메이커", "가성비", "안정적"] } },
    { id: "E06", name: "쿠보타", details: { region_name: "니가타", history: "니가타 탄레이 카라쿠치 붐의 주역.", features: "극도의 깨끗함과 담백함, 식중주의 대명사.", official_site: "", type: "sake", flavor: "karaguchi" } },
    { id: "E07", name: "남부비진", details: { region_name: "이와테", history: "1902년 창업, 지역 쌀과 물을 활용해 국제 품평회에서 다수 수상한 세계적 브랜드입니다.", features: "맑고 고운 인상의 주질과 섬세한 단맛·산미의 조화가 특징인 우아한 사케입니다.", official_site: "https://www.nanbubijin.co.jp", type: "sake", tags: ["이와테", "화사함", "수출1위"], flavor: "amaguchi" } },
    { id: "E08", name: "오토코야마", details: { region_name: "홋카이도", history: "에도 시대 전통을 계승하여 홋카이도 아사히카와의 맑은 물로 사케를 빚습니다.", features: "설산을 떠올리게 하는 시원하고 드라이한 ‘카라쿠치’ 스타일 사케의 대표격입니다.", official_site: "https://www.otokoyama.com", type: "sake", tags: ["홋카이도", "드라이", "전통"], flavor: "karaguchi" } },
    { id: "E09", name: "메이리주류 (Meiri Shurui)", details: { region_name: "이바라키", history: "에도 후기 설립, 사케·소주·리큐르 등 다양한 주류를 생산합니다.", features: "‘햐쿠넨 우메슈’ 등 진한 맛의 리큐르 분야에서 인지도가 높습니다.", official_site: "https://www.meirishurui.com", type: "other", flavor: "amaguchi", tags: ["리큐르", "햐쿠넨우메슈"] } },
    { id: "E10", name: "다카라 (Takara Shuzo)", details: { region_name: "교토", history: "1925년 설립, ‘쇼치쿠바이’ 브랜드로 알려진 일본 대표 주류 기업입니다.", features: "깔끔하고 안정된 맛을 가진 국민 브랜드 성격의 사케를 선보입니다.", official_site: "https://www.takarashuzo.co.jp", type: "sake", flavor: "karaguchi", tags: ["쇼치쿠바이", "종합주류"] } },
    { id: "E11", name: "카츠야마", details: { region_name: "미야기", history: "1688년 창업, 다테 마사무네 가문의 어용주를 만들던 미야기현 센다이의 명가입니다.", features: "높은 정미율로 구현한 밀도 높은 감칠맛과 구조감이 돋보이는 프리미엄 식중주입니다.", official_site: "https://www.katsuyama-shop.jp", type: "sake", tags: ["프리미엄", "센다이", "세련됨"], flavor: "amaguchi" } },
    { id: "E12", name: "킨료 (金陵)", details: { region_name: "카가와", history: "1789년 창업, 시코쿠 지역을 대표하는 전통 양조장입니다.", features: "온화한 산미와 부드러운 쌀 풍미로 해산물과의 궁합이 좋습니다.", official_site: "https://kinryo.co.jp", type: "sake", flavor: "balance", tags: ["시코쿠", "해산물궁합"] } },
    { id: "E13", name: "키타야 / 고쿠 (喜多屋)", details: { region_name: "후쿠오카", history: "1818년 창업, 국제 대회 IWC 챔피언 수상 경력의 명가입니다.", features: "정제된 스타일의 사케와 오크 숙성 보리소주 ‘고쿠’가 유명합니다.", official_site: "https://www.kitaya.co.jp", type: "sake", flavor: "karaguchi", tags: ["IWC챔피언", "오크숙성소주"] } },
    { id: "E14", name: "호우잔/텐부", details: { region_name: "가고시마", history: "전통 고구마 소주 '호우잔'과 최근 선보인 모던 사케 브랜드 '텐부'를 전개합니다.", features: "구수한 소주의 풍미와 맑고 깨끗한 산미의 사케를 모두 즐길 수 있는 라인업입니다.", official_site: "https://www.nishi-shuzo.co.jp", type: "shochu", tags: ["가고시마", "혁신", "고구마소주"], flavor: "balance" } },
    { id: "E15", name: "나나쿠보 (가고시마)", details: { region_name: "가고시마", history: "전통 소주 메이커가 선보이는 프리미엄 고구마 소주 브랜드입니다.", features: "고구마의 강한 향을 정제해 부드러운 단맛과 깔끔한 마무리를 강조합니다.", official_site: "", type: "shochu", flavor: "amaguchi", tags: ["프리미엄소주", "고구마소주"] } },
    { id: "E16", name: "핫카이산", details: { region_name: "니가타", history: "설산 지하수를 사용하는 니가타 대표 양조장.", features: "질리지 않는 깨끗한 맛의 올라운더 식중주.", official_site: "https://www.hakkaisan.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "E17", name: "호라이센", details: { region_name: "아이치", history: "1864년 창업, 아이치현 오쿠미카와에서 체험형 프로그램을 운영하는 지역 친화적 양조장입니다.", features: "프리미엄 라인 ‘쿠우(空)’로 대표되는 우아한 과실 향과 실크 같은 텍스처가 특징입니다.", official_site: "https://www.houraisen.co.jp", type: "sake", tags: ["아이치", "우아함", "인기주"], flavor: "amaguchi" } },
    { id: "E18", name: "이나타히메 (돗토리)", details: { region_name: "돗토리", history: "1673년 창업, 일본 신화 속 공주의 이름을 딴 역사 깊은 곳입니다.", features: "전통 양조법으로 쌀의 감칠맛을 살린 묵직하고 품위 있는 풍미입니다.", official_site: "https://www.inata.co.jp", type: "sake", flavor: "balance", tags: ["신화", "전통양조", "묵직함"] } },
    { id: "E19", name: "유키노보우샤", details: { region_name: "아키타", history: "1902년 설립, 자연 발효와 정밀한 온도 관리를 통해 아키타 사케의 정수를 보여줍니다.", features: "화사한 과실 향과 세련된 산미, 정제된 향미가 균형을 이루는 모던한 스타일입니다.", official_site: "https://www.yukinobousha.jp", type: "sake", tags: ["아키타", "효모명가", "세련됨"], flavor: "amaguchi" } },
    { id: "E20", name: "나베시마", details: { region_name: "사가", history: "IWC 챔피언 사케 수상으로 명성을 얻은 프리미엄 브랜드.", features: "화사한 향과 세련된 산미, 풍부한 단맛의 조화.", official_site: "https://www.fukuchiyo.co.jp", type: "sake", flavor: "amaguchi" } },
  ],
  F: [
    { id: "F01", name: "죠잔", details: { region_name: "후쿠이", history: "후쿠이현의 산간 지역에서 19세기 후반 설립되어 지역 지하수와 쌀로 사케를 빚어왔습니다.", features: "잡미 없이 깨끗하게 떨어지는 피니시가 특징인 드라이한 식중주 스타일입니다.", type: "sake", tags: ["후쿠이", "드라이", "강직함"], flavor: "karaguchi" } },
    { id: "F02", name: "우메노야도", details: { region_name: "나라", history: "1893년 창업, 전통 사케와 함께 생과일 리큐르 ‘아라고시’ 시리즈로 세계적인 인기를 얻었습니다.", features: "부드러운 질감의 사케와 실제 과일을 듬뿍 사용한 진한 과실 리큐르가 강점입니다.", official_site: "https://umenoyado.com", type: "liqueur", tags: ["리큐르", "아라고시", "나라"], flavor: "amaguchi" } }, 
    { id: "F07", name: "갓산", details: { region_name: "시마네", history: "1826년 설립, 일본 100대 명수로 꼽히는 시마네현 야에가키의 물을 사용합니다.", features: "녹은 눈처럼 맑고 깨끗한 주질과 은은한 단맛이 담백한 요리와 잘 어울립니다.", official_site: "https://gassan-sake.co.jp", type: "sake", tags: ["시마네", "초연수", "부드러움"], flavor: "amaguchi" } },
    { id: "F09", name: "하쿠시카", details: { region_name: "효고(나다)", history: "에도 시대부터 이어진 전통을 바탕으로 나다 사케 문화를 알리는 효고현의 대표 양조장입니다.", features: "힘 있고 드라이한 주질을 중심으로 일상에서 프리미엄까지 폭넓은 라인업을 갖췄습니다.", official_site: "https://www.hakushika.co.jp/en/", type: "sake", tags: ["나다", "전통", "클래식"], flavor: "karaguchi" } },
    { id: "F10", name: "하나노마이", details: { region_name: "시즈오카", history: "시즈오카현 하마마쓰 인근의 양조장으로 지역의 깨끗한 수자원을 적극 활용합니다.", features: "부드러운 꽃향과 멜론 계열의 은은한 과실 향이 맑은 물맛과 조화를 이룹니다.", official_site: "https://www.hananomai.co.jp", type: "sake", tags: ["시즈오카", "와인효모", "청량감"], flavor: "balance" } },
    { id: "F11", name: "닷사이블루", details: { region_name: "미국 뉴욕", history: "일본 닷사이(아사히주조)가 뉴욕 하이드파크에 설립한 해외 양조장 브랜드입니다.", features: "닷사이의 클린한 스타일에 현지 물 특성을 반영한 선명한 산미가 특징입니다.", official_site: "https://dassai.com", type: "sake", tags: ["뉴욕양조", "닷사이", "글로벌"], flavor: "amaguchi" } },
    { id: "F12", name: "치요무스비", details: { region_name: "돗토리", history: "돗토리현 사카이미나토에서 메이지 시대부터 사케와 소주를 함께 생산해 왔습니다.", features: "해안 지역 특유의 산뜻한 드라이함과 실험적인 발포성 사케 등이 유명합니다.", official_site: "https://www.chiyomusubi.co.jp", type: "sake", tags: ["돗토리", "스파클링", "인연"], flavor: "balance" } },
    { id: "F13", name: "쿠로우시", details: { region_name: "와카야마", history: "와카야마현 헤이와주조가 1866년 창업 이후 생산해 온 대표 사케 브랜드입니다.", features: "쌀의 두터운 감칠맛과 적당한 산미를 살린 범용성 높은 준마이 스타일입니다.", official_site: "https://www.heiwa-shuzou.co.jp", type: "sake", tags: ["와카야마", "감칠맛", "식중주"], flavor: "balance" } },
    { id: "F15", name: "시치다", details: { region_name: "사가", history: "사가현 텐잔주조가 설립된 이후 무여과 생 원주 스타일로 큰 인기를 얻은 브랜드입니다.", features: "여과를 최소화하여 쌀의 농밀한 풍미와 볼륨감이 강하게 느껴지는 주질이 특징입니다.", official_site: "https://www.tenzan.co.jp", type: "sake", tags: ["사가", "모던", "풍부함"], flavor: "balance" } },
    { id: "F19", name: "카이운", details: { region_name: "시즈오카", history: "시즈오카현에서 메이지 시대 설립되었으며 ‘행운을 연다’는 길조의 의미를 담고 있습니다.", features: "향과 맛의 밸런스가 좋고, 깔끔한 피니시 뒤에 남는 우아한 단맛이 인상적입니다.", official_site: "https://www.kaiunsake.co.jp", type: "sake", tags: ["시즈오카", "길조", "청량함"], flavor: "karaguchi" } },
    { id: "F03", name: "주)카네타 타마다 주조점", details: { region_name: "도호쿠", history: "도호쿠권에서 메이지 시대 설립된 전통 양조장으로 지역 밀착형 생산을 이어왔습니다.", features: "쌀의 단맛과 산미를 조화롭게 살린 클래식하고 절제된 스타일의 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "F04", name: "나가노메이죠", details: { region_name: "나가노", history: "나가노현의 산악 지대에서 지하수를 활용하여 상쾌한 주질을 추구합니다.", features: "부드러운 산미와 깨끗한 목넘김으로 산지 채소 요리와 훌륭한 궁합을 보여줍니다.", official_site: "", type: "sake" } }, 
    { id: "F05", name: "키노에네", details: { region_name: "치바", history: "에도 시대부터 사케와 발효 식품을 함께 만들어온 치바현의 유서 깊은 곳입니다.", features: "산뜻한 향과 균형 잡힌 맛을 지향하며 일상 식탁에 곁들이기 좋은 사케를 생산합니다.", official_site: "", type: "sake" } }, 
    { id: "F06", name: "나카이도", details: { region_name: "오이타", history: "지역산 보리와 지하수를 사용하여 전통적인 보리 소주를 생산해 왔습니다.", features: "구수한 곡물 향과 부드러운 목넘김이 특징인 깔끔한 스타일의 보리 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "F08", name: "베니오토메", details: { region_name: "후쿠오카", history: "1970년대 세계 최초로 참깨를 주원료로 한 증류주를 상업화한 혁신적 증류소입니다.", features: "볶은 참깨 특유의 고소한 향과 바닐라 같은 여운이 남는 독창적인 소주입니다.", official_site: "", type: "shochu", tags: ["참깨소주", "고소함", "세계최초"], flavor: "balance" } },
    { id: "F10", name: "하나노마이" },
    { id: "F14", name: "하나가키" }, 
    { id: "F16", name: "죠키겐", details: { region_name: "이시카와", history: "19세기부터 지역의 물을 사용하여 정성껏 사케를 빚어온 이시카와현의 양조장입니다.", features: "깔끔한 향과 균형 잡힌 맛을 지향하는 전형적인 식중주 스타일입니다.", official_site: "", type: "sake" } }, 
    { id: "F17", name: "이요카기야", details: { region_name: "에히메", history: "에히메현의 소규모 양조장으로 시코쿠 지역의 자원을 활용해 가족 경영을 이어왔습니다.", features: "가벼운 산미와 부드러운 단맛이 특징인 산뜻한 주질의 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "F18", name: "카쿠레이", details: { region_name: "니가타", history: "니가타현 설산 지역의 지하수를 사용하여 정통 니가타 사케를 빚습니다.", features: "단맛을 억제하고 깨끗하게 떨어지는 니가타 탄레이 카라쿠치 스타일의 정석입니다.", official_site: "", type: "sake" } }, 
    { id: "F20", name: "아야키쿠", details: { region_name: "카가와", history: "에도 말기 카가와현에서 설립되어 지역 쌀을 이용한 양조를 이어온 곳입니다.", features: "시코쿠 쌀의 부드러운 감칠맛과 담백한 끝맛이 어우러진 식중주 스타일입니다.", official_site: "", type: "sake" } },
  ],
  G: [
    { id: "G02", name: "호오비덴", details: { region_name: "토치기", history: "1872년 창업, 니코 산맥의 지하수와 지역 쌀을 사용하여 양조합니다.", features: "멜론이나 머스캣을 연상시키는 화려한 향과 풍부한 단맛이 돋보이는 모던 사케입니다.", official_site: "https://hououbiden.jp", type: "sake", tags: ["화사함", "인기주", "토치기"], flavor: "amaguchi" } },
    { id: "G08", name: "자쿠", details: { region_name: "미에", history: "미에현 스즈카에서 1869년 설립, G7 서밋 건배주로 선정되어 세계적 주목을 받았습니다.", features: "투명한 과실 향과 정교한 단맛·산미의 조화가 세련된 인상을 주는 모던 명작입니다.", official_site: "https://www.shimizu-seizaburo.jp", type: "sake", tags: ["G7공식주", "우아함", "미에"], flavor: "amaguchi" } },
    { id: "G09", name: "햐쿠쥬로", details: { region_name: "기후", history: "가부키 배우의 이름에서 따온 강렬한 이미지로 브랜드를 전개하는 기후현의 양조장입니다.", features: "붉은 가부키 마스크 레이블처럼 향과 바디감이 강렬한 존재감 있는 스타일입니다.", official_site: "https://hyakujuro-sake.com", type: "sake", tags: ["가부키", "강렬함", "기후"], flavor: "karaguchi" } },
    { id: "G13", name: "라이후쿠", details: { region_name: "이바라키", history: "1716년 창업, 딸기나 해바라기 등 다양한 꽃에서 분리한 꽃 효모를 사용하는 것으로 유명합니다.", features: "꽃 효모 특유의 다채롭고 신선한 향이 화사하게 표현된 사케입니다.", official_site: "https://www.raifuku.co.jp", type: "sake", tags: ["꽃효모", "다채로움", "이바라키"], flavor: "amaguchi" } },
    { id: "G14", name: "이즈모후지", details: { region_name: "시마네", history: "신들의 고향 시마네현 이즈모에서 19세기부터 사케를 빚어온 지역 브랜드입니다.", features: "일본주 특유의 은은한 감칠맛과 부드러운 단맛을 살린 차분한 식중주 스타일입니다.", official_site: "https://www.izumofuji.co.jp", type: "sake", tags: ["이즈모", "수작업", "전통"], flavor: "amaguchi" } },
    { id: "G15", name: "하쿠라쿠세이", details: { region_name: "미야기", history: "1873년 설립된 니이자와주조의 브랜드로 ‘궁극의 식중주’라는 독보적인 모토를 가졌습니다.", features: "향이 과하지 않고 음식의 맛을 완벽하게 뒷받침하도록 설계된 매우 깨끗한 주질입니다.", official_site: "https://niizawa-brewery.co.jp", type: "sake", tags: ["궁극의식중주", "미야기", "깔끔함"], flavor: "karaguchi" } },
    { id: "G19", name: "사츠마무소", details: { region_name: "가고시마", history: "가고시마현에서 1950년대 설립되어 사츠마 고구마 소주를 대표하는 브랜드 중 하나입니다.", features: "깊은 단맛과 묵직한 바디감을 가진 정통 스타일로 뜨겁게 마실 때 맛이 더욱 살아납니다.", official_site: "https://www.satsuma-musou.co.jp", type: "shochu", tags: ["가고시마", "고구마소주", "전통숙성"], flavor: "balance" } },
    { id: "G01", name: "일로사케", details: { region_name: "큐레이션", history: "일본 각지의 우수한 사케를 한국에 소개하며 여러 양조장과 파트너십을 맺고 있습니다.", features: "다양한 지역과 스타일의 사케를 선별하여 소개하는 플랫폼적인 성격이 강합니다.", official_site: "", type: "other" } }, 
    { id: "G03", name: "카메노우미", details: { region_name: "나가노", history: "나가노현의 산악 지대에서 깨끗한 물과 지역 쌀을 바탕으로 양조하는 소규모 브랜드입니다.", features: "부드러운 과실 향과 둥근 산미를 가진 편안하고 세련된 모던 사케가 중심입니다.", official_site: "", type: "sake" } }, 
    { id: "G04", name: "미코츠루", details: { region_name: "나가노", history: "현대의 젊은 감각을 사케에 투영하여 새로운 스타일을 전개하는 나가노의 양조장입니다.", features: "화사한 향과 산뜻한 산미가 차갑게 마셨을 때 더욱 돋보이는 모던 스타일입니다.", official_site: "", type: "sake" } }, 
    { id: "G05", name: "킷도,츠루우메", details: { region_name: "와카야마", history: "와카야마현 헤이와주조의 브랜드로 사케 '킷도'와 리큐르 '츠루우메'를 전개합니다.", features: "경쾌한 사케와 실제 유자 과즙을 듬뿍 사용한 상큼한 리큐르가 특징입니다.", type: "sake", tags: ["와카야마", "젊은감각", "매실주"], flavor: "amaguchi" } }, 
    { id: "G06", name: "일로사케" }, 
    { id: "G07", name: "이와노이", details: { region_name: "치바", history: "치바현 해안가 인근 환경에서 미네랄감 있는 사케를 빚어온 양조장입니다.", features: "해산물과 잘 어울리도록 깨끗하고 산뜻한 산미를 살린 주질을 지향합니다.", official_site: "", type: "sake" } }, 
    { id: "G10", name: "아카루이노우손", details: { region_name: "가고시마", history: "‘밝은 농촌’이라는 이름으로 지역 농업과의 연결을 강조하는 고구마 소주 명가입니다.", features: "고구마의 구수함에 부드러움을 더해 마시기 편한 밝은 이미지를 구현했습니다.", official_site: "", type: "shochu" } }, 
    { id: "G11", name: "크래프츠맨타다", details: { region_name: "후쿠오카", history: "전통 보리 소주를 현대적 감각으로 재해석하여 전개하는 후쿠오카의 브랜드입니다.", features: "보리의 고소함을 세련되게 다듬어 위스키처럼 즐길 수 있는 모던 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "G12", name: "미치자쿠라", details: { region_name: "야마가타", history: "벚꽃의 이미지를 담아 산뜻하고 마시기 쉬운 사케를 목표로 하는 야마가타의 브랜드입니다.", features: "은은한 꽃향과 부드러운 단맛이 일품인 봄날 같은 사케를 선보입니다.", official_site: "", type: "sake" } }, 
    { id: "G16", name: "에시칼스피리츠", details: { region_name: "혁신증류", history: "사케 술지게미를 재활용하는 업사이클 콘셉트의 젊은 증류 프로젝트입니다.", features: "술지게미의 풍미에 각종 보태니컬을 더한 개성적인 크래프트 진을 생산합니다.", official_site: "", type: "other" } }, 
    { id: "G17", name: "긴자노스즈메", details: { region_name: "오이타", history: "세련된 디자인과 대중적인 맛으로 입문자에게도 사랑받는 보리 소주 브랜드입니다.", features: "부드럽고 깔끔한 맛 덕분에 일상에서 편하게 즐기기 좋은 정석적인 보리 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "G18", name: "사케노카마쿠라", details: { region_name: "큐레이션", history: "다양한 양조장의 우수한 제품들을 테마별로 큐레이션해 소개하는 편집숍형 브랜드입니다.", features: "전국 각지의 숨은 명주를 한자리에서 제안하는 다양성이 특징입니다.", official_site: "", type: "other" } }, 
    { id: "G20", name: "류카", details: { region_name: "오키나와", history: "남국 오키나와의 기후와 재료를 살려 강렬하고 존재감 있는 증류주를 만듭니다.", features: "향기롭고 깊은 맛을 가진 증류주가 많아 칵테일 베이스로도 훌륭합니다.", official_site: "", type: "other" } },
  ],
  H: [
    { id: "H02", name: "야마모토", details: { region_name: "아키타", history: "1901년 창업, 모던한 디자인과 화이트 와인 같은 상큼한 맛으로 인기를 얻은 아키타 명가입니다.", features: "세련된 산미와 깨끗한 과실 향이 돋보이는 ‘블랙 라벨’ 시리즈가 상징적입니다.", official_site: "https://www.yamamoto-jizake.co.jp", type: "sake", tags: ["아키타", "혁신", "산미"], flavor: "balance" } },
    { id: "H03", name: "야마가타마사무네", details: { region_name: "야마가타", history: "1898년 설립, 명검 ‘마사무네’처럼 날렵하게 끊어지는 주질을 추구합니다.", features: "단단한 뼈대와 드라이한 맛이 매력적인 정통파 사케의 면모를 보여줍니다.", official_site: "https://ok-itou.com", type: "sake", tags: ["야마가타", "경수", "샤프함"], flavor: "karaguchi" } },
    { id: "H10", name: "쿠메지마노쿠메센", details: { region_name: "오키나와", history: "쿠메섬의 맑은 물과 전통 흑국균을 사용하여 깊은 아와모리를 빚는 양조장입니다.", features: "구수한 향과 묵직한 맛부터 오크통 숙성 스타일까지 폭넓은 아와모리를 선보입니다.", official_site: "https://kumesen.co.jp", type: "awamori", tags: ["오키나와", "아와모리", "숙성주"], flavor: "balance" } },
    { id: "H11", name: "슈호", details: { region_name: "야마가타", history: "지역의 쌀과 물을 활용해 멜론이나 바나나 같은 화사한 향을 구현하는 양조장입니다.", features: "상쾌한 산미와 입안 가득 퍼지는 꽃향기가 일품인 화려한 스타일의 사케입니다.", official_site: "https://www.akahoshi-shuzo.co.jp", type: "sake", tags: ["야마가타", "화려함", "프리미엄"], flavor: "amaguchi" } },
    { id: "H12", name: "록카센", details: { region_name: "야마가타", history: "전통을 현대적으로 재해석하여 누구나 좋아할 만한 깔끔한 기획 사케를 선보입니다.", features: "스파클링 사케 등 다양한 시도를 통해 산뜻하고 현대적인 맛의 스펙트럼을 제공합니다.", official_site: "https://rokkasen.co.jp", type: "sake", tags: ["야마가타", "대중적", "깔끔함"], flavor: "balance" } },
    { id: "H13", name: "토우코우", details: { region_name: "야마가타", history: "1597년 창업, 우에스기 가문의 어용주를 만들던 품위 있는 역사를 가진 양조장입니다.", features: "쌀의 깊은 맛과 균형 잡힌 산미가 어우러진 격식 있는 정통파 주질이 특징입니다.", official_site: "https://www.tohko-sake.com", type: "sake", tags: ["야마가타", "역사적", "깊은맛"], flavor: "balance" } },
    { id: "H15", name: "아카부", details: { region_name: "이와테", history: "젊은 토지를 중심으로 부활하여 쥬시한 과실 향으로 화제가 된 이와테의 신성입니다.", features: "강렬한 생동감과 현대적인 산미·단맛의 밸런스가 뛰어난 모던 사케입니다.", official_site: "https://www.akabu1.com", type: "sake", tags: ["이와테", "부활", "젊은감각"], flavor: "amaguchi" } },
    { id: "H20", name: "카메이즈미", details: { region_name: "고치", history: "1897년 창업, 고치현의 실험적 효모 기술을 활용해 독창적인 맛을 창조합니다.", features: "트로피컬한 과실 향과 높은 산미가 디저트 와인 같은 인상을 주는 모던 사케입니다.", official_site: "https://kameizumi.co.jp", type: "sake", tags: ["고치", "파인애플향", "CEL24"], flavor: "amaguchi" } },
    { id: "H01", name: "유키노비진", details: { region_name: "아키타", history: "도심 빌딩 내에서 사계절 양조를 수행하며 온도 관리에 철저한 신생 양조장입니다.", features: "잡미 없이 맑고 날카롭게 떨어지는 피니시가 돋보이는 깨끗한 주질이 특징입니다.", official_site: "", type: "sake" } }, 
    { id: "H04", name: "벤텐", details: { region_name: "야마가타", history: "여신의 이름을 딴 브랜드로, 우아하고 섬세한 인상을 주는 사케를 지향합니다.", features: "부드러운 단맛과 여성적인 향미가 어우러진 우아한 스타일의 사케가 많습니다.", official_site: "", type: "sake" } }, 
    { id: "H05", name: "가산류", details: { region_name: "야마가타", history: "자연의 이미지를 담은 이름처럼 상쾌하고 경쾌한 주질을 목표로 하는 브랜드입니다.", features: "산뜻한 산미와 맑은 향을 가진 모던 사케로 부담 없이 즐기기 좋은 스타일입니다.", official_site: "", type: "sake" } }, 
    { id: "H06", name: "타카", details: { region_name: "야마구치", history: "젊은 양조 팀이 운영하며 쌀의 쌉쌀함과 탄탄한 바디감을 강조하는 모던 브랜드입니다.", features: "단맛을 억제하고 드라이한 맛을 전면에 내세워 차별화된 개성을 보여줍니다.", official_site: "", type: "sake" } }, 
    { id: "H07", name: "미요시", details: { region_name: "서일본", history: "소규모 양조장들이 가족 경영을 통해 정성껏 빚어내는 지역 밀착형 브랜드입니다.", features: "부드러운 단맛과 산미를 가진 전형적인 식중주 스타일의 사케가 중심입니다.", official_site: "", type: "sake" } }, 
    { id: "H08", name: "간기", details: { region_name: "야마구치", history: "숯 여과를 하지 않는 무여과 방식을 고수하여 쌀의 생동감을 전달하는 양조장입니다.", features: "여과를 최소화하여 쌀 본연의 질감과 깊은 감칠맛을 그대로 느낄 수 있는 주질입니다.", official_site: "", type: "sake" } }, 
    { id: "H09", name: "우라자토", details: { region_name: "모던양조", history: "내추럴 와인 같은 감성의 젊은 양조가들이 이끄는 모던 사케 브랜드입니다.", features: "상큼한 과실 향과 가벼운 바디로 사케 입문자도 편안하게 즐길 수 있는 맛입니다.", official_site: "", type: "sake" } }, 
    { id: "H14", name: "Innocent", details: { region_name: "혁신브랜드", history: "내추럴·와일드 발효의 이미지를 담은 최근 등장한 실험적인 브랜드입니다.", features: "산미와 개성적인 향을 과감하게 드러내어 칵테일처럼 즐길 수 있는 유니크함이 특징입니다.", official_site: "", type: "sake" } }, 
    { id: "H16", name: "야마니쿠모가", details: { region_name: "신세대양조", history: "실험적인 제법을 시도하는 젊은 세대의 브랜드로 매니아층을 타깃으로 합니다.", features: "산미와 개성이 강해 독특한 사케 경험을 찾는 이들에게 어울리는 주질입니다.", official_site: "", type: "sake" } }, 
    { id: "H17", name: "아키토라", details: { region_name: "고치", history: "고치의 해산물 요리와 밸런스를 맞추기 위해 탄생한 드라이 사케 브랜드입니다.", features: "강한 산미와 드라이한 맛으로 진한 요리와 함께 마셔도 훌륭한 식중주입니다.", official_site: "", type: "sake" } }, 
    { id: "H18", name: "코우치현", details: { region_name: "지역홍보", history: "고치현의 우수한 사케 문화를 알리는 홍보 거점으로 다양한 지역주를 소개합니다.", features: "산뜻하고 드라이한 고치 특유의 해산물 친화형 사케들을 한자리에서 만날 수 있습니다.", official_site: "", type: "other" } }, 
    { id: "H19", name: "토요노우메", details: { region_name: "리큐르", history: "지역 과일의 신선함을 담아내는 리큐르 전문 브랜드입니다.", features: "상큼한 산미와 기분 좋은 단맛이 특징인 입가심용으로 훌륭한 과실주들입니다.", official_site: "", type: "liqueur" } },
  ],
  J: [
    { id: "J01", name: "아즈마쵸", details: { region_name: "사가", history: "에도 말기 설립, 지역 밀착형 사케를 빚어온 전통 양조장.", features: "쌀의 단맛과 산미가 균형을 이룸.", official_site: "", type: "sake", flavor: "balance" } },
    { id: "J05", name: "케센토하루카", details: { region_name: "이와테", history: "지역 부흥을 목표로 기획된 브랜드.", features: "깔끔한 드라이함과 가벼운 산미.", official_site: "", type: "sake", flavor: "karaguchi" } },
    { id: "J06", name: "일로사케 판매부스", details: COMMON_SERVICE_DETAIL },
    { id: "J07", name: "일로사케 이벤트", details: COMMON_SERVICE_DETAIL },
    { id: "J10", name: "후쿠쵸", details: { region_name: "히로시마", history: "유명 양조장 이마다주조의 브랜드로 부드럽고 섬세한 긴조 스타일을 지향합니다.", features: "은은한 향과 섬세한 단맛이 돋보이는 히로시마의 대표적인 모던 사케입니다.", official_site: "https://www.imada.jp", type: "sake", flavor: "amaguchi" } },
    { id: "J11", name: "고젠슈", details: { region_name: "오카야마", history: "전통 제법과 오마치 쌀 100% 사용으로 요구르트 같은 개성적 산미를 선사합니다.", features: "독특한 젖산 산미와 깊은 풍미가 어우러진 오카야마의 명물 사케입니다.", official_site: "https://www.gozenshu.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "J17", name: "리브롬", details: { region_name: "후쿠오카", history: "과일·허브 등을 활용해 실험적인 크래프트 사케를 빚는 신생 양조장입니다.", features: "전통의 틀을 깬 다채로운 재료의 조화와 신선한 맛이 특징입니다.", official_site: "https://www.librom.jp", type: "other", tags: ["크래프트"] } },
    { id: "J02", name: "아즈마츠루", details: { region_name: "사가", history: "20세기 초 사가현에서 설립되어 지역 쌀을 중심으로 양조를 이어온 브랜드입니다.", features: "부드러운 단맛과 온화한 향을 가진 전형적인 클래식 식중주 스타일입니다.", official_site: "", type: "sake" } }, 
    { id: "J03", name: "후쿠우미", details: { region_name: "기획브랜드", history: "현대적 감각의 라벨과 맛으로 젊은 층에게 어필하는 모던 사케 컨셉 레이블입니다.", features: "여러 양조장의 특색 있는 사케들을 세련되게 모아 소개하는 것이 강점입니다.", official_site: "", type: "sake" } }, 
    { id: "J04", name: "무소우", details: { region_name: "모던사케", history: "나가노 등지의 양조장들이 ‘꿈속의 상상’이라는 모토로 재정비한 라인업입니다.", features: "과실 향과 산미를 살려 캐주얼한 안주와 즐기기 좋은 경쾌한 주질을 지녔습니다.", official_site: "", type: "sake" } }, 
    { id: "J08", name: "센게츠", details: { region_name: "구마모토", history: "100년 이상 히토요시의 맑은 물로 쌀 소주를 빚어온 구마모토의 명가입니다.", features: "부드러운 목넘김과 은은한 곡물 향이 조화로운 맑은 타입의 쌀 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "J09", name: "소우텐덴", details: { region_name: "미야기", history: "지진 이후 지역 복구를 상징하며 해산물 궁합을 최우선으로 설계된 브랜드입니다.", features: "깔끔하고 산뜻한 드라이함이 특징인 항구 도시 미야기 특유의 주질입니다.", official_site: "", type: "sake" } }, 
    { id: "J12", name: "타이쇼노츠루", details: { region_name: "오카야마", history: "메이지~타이쇼 시대부터 오카야마 지역에 뿌리 내린 유서 깊은 브랜드입니다.", features: "화려함보다는 쌀의 깊은 맛과 부드러운 단맛에 집중한 식중주 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "J13", name: "츠쿠시", details: { region_name: "후쿠오카", history: "수십 년간 규슈 지역에서 큰 사랑을 받아온 후쿠오카의 정통 보리 소주입니다.", features: "보리를 구운 듯한 고소함과 스모키한 여운이 매력적인 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "J14", name: "시게마스", details: { region_name: "후쿠오카", history: "높은 도정비와 정성 어린 양조로 알려진 후쿠오카의 프리미엄급 브랜드입니다.", features: "잡미 없이 정갈한 주질과 섬세한 단맛이 돋보이는 고품격 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "J15", name: "와카나미", details: { region_name: "후쿠오카", history: "젊은 양조자와 여성 토지가 이끄는 부드러운 감성의 모던 양조장입니다.", features: "부드러운 파도처럼 밀려오는 섬세한 산미와 맛의 조화가 탁월한 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "J16", name: "키쿠비진", details: { region_name: "규슈전통", history: "20세기 초반부터 예술가들 사이에서 회자된 전통과 권위의 브랜드입니다.", features: "진중한 쌀맛과 깊은 감칠맛을 정직하게 표현한 정통파 스타일의 사케입니다.", official_site: "", type: "sake" } },
  ],
  K: [
    { id: "K01", name: "미요키쿠", details: { region_name: "도쿠시마", history: "실험적인 양조와 개성 강한 산미, 팝한 라벨 디자인으로 지지층이 두터운 양조장입니다.", features: "내추럴 와인과 유사한 뚜렷한 산미와 쥬시한 단맛이 특징인 모던 사케입니다.", official_site: "https://www.miyoshikiku.com", type: "sake", tags: ["내추럴", "산미", "개성적"], flavor: "amaguchi" } },
    { id: "K02", name: "카제노모리", details: { region_name: "나라", history: "무여과 나마(생주) 중심 양조의 선구자.", features: "자연 탄산과 청포도·허브 같은 상큼한 향.", official_site: "https://www.yucho-sake.jp", type: "sake", flavor: "amaguchi" } },
    { id: "K03", name: "유호", details: { region_name: "이시카와", history: "19세기 후반부터 이시카와현 해변가에서 해산물 맞춤형 사케를 빚어온 곳입니다.", features: "해산물과 완벽히 어우러지는 풍부한 우마미와 숙성된 산미가 일품인 식중주입니다.", official_site: "https://www.yuho-sake.jp", type: "sake", tags: ["이시카와", "우마미", "식중주"], flavor: "balance" } },
    { id: "K04", name: "코츠즈미", details: { region_name: "효고", history: "1849년 창업, 예술적인 병 디자인과 함께 품격 있는 사케 문화를 지향하는 양조장입니다.", features: "예술적인 라벨만큼이나 정교하게 조율된 부드러운 단맛과 맑은 피니시가 특징입니다.", official_site: "https://www.kotsuzumi.co.jp", type: "sake", tags: ["효고", "우아함", "예술적"], flavor: "balance" } },
    { id: "K05", name: "사와노츠루", details: { region_name: "효고", history: "나다를 대표하는 전통 대형 양조장.", features: "힘 있고 드라이한 주질이 특징.", official_site: "https://www.sawanotsuru.co.jp", type: "sake", flavor: "karaguchi" } },
  ],
  L: [
    { id: "L01", name: "사카야코리아 판매부스", details: COMMON_SERVICE_DETAIL },
    { id: "L02", name: "이와테메이죠", details: { region_name: "이와테", history: "이와테현의 차가운 기후에서 지역 자원을 사용해 빚어낸 전통 사케입니다.", features: "북국의 깨끗함을 닮아 잡미가 없고 담백한 전형적인 식중주 스타일입니다.", official_site: "", type: "sake" } },
    { id: "L03", name: "CR트레이딩", details: { region_name: "수입사", history: "일본 주류의 해외 유통 전문사.", features: "다양한 양조장 브랜드를 큐레이션하여 소개.", official_site: "", type: "other" } },
    { id: "L05", name: "CR트레이딩판매부스", details: COMMON_SERVICE_DETAIL },
  ],
  M: [
    { id: "M01", name: "사카야코리아", details: COMMON_SERVICE_DETAIL },
    { id: "M03", name: "스이센", details: { region_name: "이와테", history: "2011년 쓰나미 피해를 극복하고 부활한 지역 부흥의 상징적 양조장입니다.", features: "상큼하고 드라이한 주질이 해산물과 탁월한 마리아주를 이루는 사케입니다.", official_site: "https://www.suisenshuzo.jp", type: "sake", flavor: "karaguchi" } },
    { id: "M04", name: "초카이산", details: { region_name: "아키타", history: "초카이산 기슭의 만년설 복류수를 사용하는 자연 친화적 양조장입니다.", features: "맑고 부드러운 주질에 화사한 꽃향기를 더한 우아한 다이긴조가 명품입니다.", official_site: "https://www.tenju.co.jp", type: "sake", flavor: "amaguchi" } },
    { id: "M08", name: "아키타세이슈", details: { region_name: "아키타", history: "20세기 초부터 아키타의 사계절을 담은 정통 사케를 빚어온 명가입니다.", features: "깨끗한 주질 속에 은은하게 배어 나오는 과실 향과 산미가 매력적인 모던 타입입니다.", official_site: "https://www.akitaseishu.co.jp", type: "sake", flavor: "balance" } },
    { id: "M10", name: "마츠노츠카사", details: { region_name: "시가", history: "19세기 후반부터 시가현 비와호 인근의 테루아를 사케에 담아온 명소입니다.", features: "지역 유기농 쌀을 사용한 라인업 등 대지의 풍미와 감칠맛이 살아있는 명주입니다.", official_site: "https://www.matsunotsukasa.com", type: "sake", tags: ["시가", "테루아", "우아함"], flavor: "balance" } },
    { id: "M11", name: "반슈잇콘", details: { region_name: "효고", history: "효고현 반슈 지역을 대표하는 양조장.", features: "깔끔한 드라이함과 쌀의 감칠맛의 조화.", official_site: "https://www.banshu-ikkon.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "M12", name: "아베", details: { region_name: "니가타", history: "혁신적인 젊은 양조장.", features: "풍부한 산미와 감칠맛의 모던 스타일.", official_site: "https://abe-sake.com", type: "sake", flavor: "balance" } },
    { id: "M05", name: "사쿠라가오", details: { region_name: "이와테", history: "벚꽃의 서정적인 이미지를 콘셉트로 메이지 시대 설립된 양조장입니다.", features: "부드러운 단맛과 정제된 향을 지녀 매일 마셔도 질리지 않는 편안한 스타일입니다.", official_site: "", type: "sake" } }, 
    { id: "M06", name: "하마치도리", details: { region_name: "이와테", history: "이와테현 해안 도시 미야코에서 지역 수산물과 조화로운 사케를 생산합니다.", features: "상쾌한 산미와 드라이한 주질이 초밥이나 해산물 요리의 맛을 돋워줍니다.", official_site: "", type: "sake" } }, 
    { id: "M07", name: "야히코주조", details: { region_name: "니가타", history: "야히코 신사의 성스러운 물을 사용하여 전통을 이어가는 니가타의 양조장입니다.", features: "니가타 사케답게 매우 깔끔하고 높은 안정성을 가진 담백한 카라쿠치 스타일입니다.", official_site: "", type: "sake" } },
  ],
  P: [
    { id: "P02", name: "텐비", details: { region_name: "야마구치", history: "2020년 런칭 후 '사케계의 초신성'으로 불리며 구하기 힘든 술이 된 프리미엄 브랜드입니다.", features: "머스캣 같은 산미와 투명한 단맛이 정교하게 조율된 매우 세련된 모던 사케입니다.", official_site: "https://www.abe-sake.com/tenbi", type: "sake", tags: ["야마구치", "신성", "프루티"], flavor: "amaguchi" } },
    { id: "P03", name: "무츠핫센", details: { region_name: "아오모리", history: "1775년 창업한 하치노헤주조의 브랜드.", features: "화사한 과실 향과 상쾌한 맛.", official_site: "https://mutsu8000.com", type: "sake", flavor: "amaguchi" } },
    { id: "P09", name: "히타카미", details: { region_name: "미야기", history: "스시와의 궁합을 위해 탄생한 브랜드.", features: "날카롭고 담백한 드라이함.", official_site: "https://www.hidakami.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "P11", name: "에이쿤", details: { region_name: "교토", history: "1895년 창업, 교토 후시미의 부드러운 물을 사용하는 대표적인 정통 명가입니다.", features: "기품 있는 감칠맛과 정갈한 주질로 교토 사케의 우아함을 가장 잘 보여줍니다.", official_site: "https://www.eikun.com", type: "sake", flavor: "balance" } },
    { id: "P13", name: "류진/오제노유키도케", details: { region_name: "군마", history: "군마현 오제 국립공원의 맑은 이미지를 담아 시원한 주질을 선보이는 브랜드입니다.", features: "눈 녹은 물처럼 맑은 청량감과 산뜻한 산미가 일품인 드라이한 스타일입니다.", official_site: "https://www.ryujin-sake.co.jp", type: "sake", flavor: "amaguchi" } },
    { id: "P14", name: "스가타", details: { region_name: "토치기", history: "1879년 창업, 정통 수작업 양조 방식을 고집하는 토치기현의 실력파 양조장입니다.", features: "무여과 생주 특유의 묵직한 바디감과 열대 과일 같은 임팩트 있는 향이 일품입니다.", official_site: "https://www.kodama-jizake.co.jp", type: "sake", flavor: "amaguchi" } },
    { id: "P01", name: "히라이즈미혼포", details: { region_name: "아키타", history: "아키타현에서 전통 야마하이 제법에 특화되어 복합적인 맛을 빚는 양조장입니다.", features: "야마하이 특유의 젖산 산미와 깊은 우마미가 시간이 갈수록 진해지는 주질입니다.", official_site: "", type: "sake" } }, 
    { id: "P04", name: "기쿄", details: { region_name: "나가노", history: "나가노현의 지역 자원을 활용하여 전통의 가치를 지키는 소규모 양조장입니다.", features: "매끄러운 목넘김과 온화한 산미로 일상에서 캐주얼하게 즐기기 좋은 편안한 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "P05", name: "마치다슈죠", details: { region_name: "군마", history: "젊은 감각의 양조를 통해 사케와 소주 모두에서 개성을 뽐내는 군마의 명소입니다.", features: "쥬시한 과실 향이 돋보이는 모던 사케 라인업으로 큰 인기를 얻고 있습니다.", official_site: "", type: "sake" } }, 
    { id: "P06", name: "나카시마야", details: { region_name: "야마구치", history: "주구쿠 지역의 전통을 계승하며 소량 생산으로 품질을 엄격히 관리하는 곳입니다.", features: "정직한 쌀맛과 묵직한 감칠맛을 지향하는 진중한 스타일의 식중주입니다.", official_site: "", type: "sake" } }, 
    { id: "P07", name: "야마탄마사무네", details: { region_name: "에히메", history: "20세기 초반부터 이름을 알려온 에히메현의 세련된 브랜드입니다.", features: "첫 모금의 화려한 향 이후에 깔끔하게 드라이해지는 구조적인 맛이 특징입니다.", official_site: "", type: "sake" } }, 
    { id: "P08", name: "에헤지 하쿠류", details: { region_name: "후쿠이", history: "후쿠이현의 명찰 에이헤이지 인근에서 맑은 물로 사케를 빚는 유서 깊은 곳입니다.", features: "잡미 없는 맑고 단아한 주질로 차분한 단맛과 산미의 조화가 탁월합니다.", official_site: "", type: "sake" } }, 
    { id: "P10", name: "겐콘이치", details: { region_name: "미야기", history: "미야기현의 신흥 강자로 스시와의 완벽한 페어링을 목표로 개발된 브랜드입니다.", features: "특유의 짭짤한 미네랄감과 드라이함이 초밥의 맛을 극대화해주는 설계입니다.", official_site: "", type: "sake" } }, 
    { id: "P15", name: "카모킨슈", details: { region_name: "히로시마", history: "히로시마의 온화한 기후를 닮아 부드럽고 상큼한 식중주 스타일을 선보입니다.", features: "다양한 요리와 무난하게 어울리면서도 세련된 산미가 식욕을 돋워줍니다.", official_site: "", type: "sake" } },
  ],
  Q: [
    { id: "Q01", name: "하기노츠루/히와타", details: { region_name: "미야기", history: "인기 많은 모던 양조장.", features: "산미와 단맛의 균형이 좋은 식중주.", official_site: "", type: "sake", flavor: "balance" } },
    { id: "Q04", name: "더블유/호라이", details: { region_name: "기후", history: "와인 같은 향과 산미를 강조.", features: "화사한 향기와 선명한 캐릭터.", official_site: "", type: "sake", flavor: "amaguchi" } },
    { id: "Q05", name: "세키토바/다이야메", details: { region_name: "가고시마", history: "현대 소주 붐을 이끈 대표 브랜드.", features: "다이야메는 라이치 향이 나는 고구마 소주.", official_site: "", type: "shochu", flavor: "amaguchi" } },
    { id: "Q09", name: "시메하리츠루", details: { region_name: "니가타", history: "1819년 창업, 니가타 3대 명주 중 하나로 꼽히는 전설적인 브랜드입니다.", features: "향·맛·피니시의 밸런스가 완벽하며 투명하고 담백한 탄레이 카라쿠치의 정점입니다.", official_site: "https://www.shimeharitsuru.co.jp", type: "sake", flavor: "karaguchi" } },
    { id: "Q11", name: "하네야", details: { region_name: "도야마", history: "모든 라인을 다이긴조 기준으로 양조.", features: "화사한 향과 경쾌함.", official_site: "", type: "sake", flavor: "amaguchi" } },
    { id: "Q02", name: "자루소호라이", details: { region_name: "가나가와", history: "‘청량한 계곡물’을 모티브로 하여 군더더기 없는 깔끔한 맛을 추구하는 브랜드입니다.", features: "계곡물 같은 서늘한 청량감과 가벼운 드라이함이 특징인 식전·식중주입니다.", official_site: "", type: "sake" } }, 
    { id: "Q03", name: "쥬하치자카리", details: { region_name: "오카야마", history: "오카야마현에서 19세기 중반부터 이어온 정통파 남성적 스타일의 양조장입니다.", features: "쌀의 질감을 묵직하게 살려 드라이하면서도 깊은 우마미가 느껴지는 파워풀한 주질입니다.", official_site: "", type: "sake" } }, 
    { id: "Q06", name: "쿠로이사니시키", details: { region_name: "가고시마", history: "흑누룩 사용 전통 제조법을 계승하며 농밀한 단맛의 고구마 소주를 빚습니다.", features: "전통 방식 그대로의 묵직한 바디감과 고구마의 진한 풍미를 느낄 수 있는 소주입니다.", official_site: "", type: "shochu" } }, 
    { id: "Q07", name: "BO", details: { region_name: "가고시마", history: "가고시마의 보리 소주를 현대적인 감각으로 재해석하여 세련되게 브랜딩했습니다.", features: "잡미를 없앤 깔끔한 스타일로 하이볼 등 다양한 방식으로 즐기기 좋습니다.", official_site: "", type: "shochu" } }, 
    { id: "Q08", name: "다이나", details: { region_name: "비옥한대지", history: "비옥한 대지의 쌀을 모티브로 삼아 대중적인 편안함을 지향하는 사케 브랜드입니다.", features: "풍부한 곡물감과 부드러운 단맛이 일품이며 포근한 인상을 주는 식중주입니다.", official_site: "", type: "sake" } }, 
    { id: "Q10", name: "츄아이", details: { region_name: "토치기", history: "현대적 감각의 준마이·긴조 사케에 집중하여 화려한 스타일을 선보이는 양조장입니다.", features: "열대 과일 같은 향과 입안 가득 채우는 풍부한 단맛의 모던 사케가 주력입니다.", official_site: "", type: "sake" } }, 
    { id: "Q12", name: "야마노고토부키", details: { region_name: "후쿠오카", history: "전통 양조의 틀 안에서 바나나·멜론 계열의 화사한 향을 가미한 후쿠오카 명가입니다.", features: "경쾌한 산미와 화사한 향으로 젊은 층에게도 인기가 많은 마시기 편한 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "Q13", name: "보우지마야", details: { region_name: "기후", history: "숙성주 생산에 특화되어 쌀의 강력한 파워를 사케에 담아내는 기후현의 브랜드입니다.", features: "장기 숙성에서 오는 깊은 향과 묵직한 바디감이 매력적인 매니아용 사케입니다.", official_site: "", type: "sake" } }, 
    { id: "Q14", name: "와카무스메", details: { region_name: "야마구치", history: "‘젊은 여인’의 상큼함을 콘셉트로 쥬시한 과실미를 선사하는 브랜드입니다.", features: "상큼한 감귤류 산미와 쥬시한 향이 세련되게 어우러진 여름 같은 사케입니다.", official_site: "", type: "sake" } },
  ],
  R: [
    { id: "R01", name: "무기시루", details: { region_name: "군마", history: "군마현 마치다주조 계열에서 생산하며 볶은 보리의 향을 강조한 소주 브랜드입니다.", features: "한 모금만으로도 곡물의 고소한 풍미가 가득 퍼지는 정석적인 보리 소주입니다.", official_site: "https://www.machidashuzo.com", type: "shochu", flavor: "karaguchi" } },
    { id: "R02", name: "카가미즈진저쇼츄리퍼블릭", details: { region_name: "와카야마", history: "특산물 생강을 증류해 만든 크래프트 소주.", features: "알싸하고 스파이시한 향, 하이볼 추천.", official_site: "", type: "other" } },
    { id: "R04", name: "덴신 잇본기", details: { region_name: "후쿠이", history: "후쿠이의 명가 잇본기주조의 브랜드.", features: "섬세한 단맛과 감칠맛의 단아한 주질.", official_site: "https://www.ip-pongi.co.jp", type: "sake", flavor: "balance" } },
    { id: "R03", name: "토요카류스이센", details: { region_name: "도심양조", history: "도심 라이프스타일과 협업하여 생산되는 실험적인 크래프트 사케/소주 프로젝트입니다.", features: "부드럽고 가벼운 주질로 일상에서 부담 없이 즐길 수 있는 세련된 맛을 지향합니다.", official_site: "", type: "other" } },
  ],
  V: [
    { id: "V01", name: "메멜트", details: { region_name: "푸드", history: "디저트", features: "부드럽게 녹아내리는 치즈나 버터를 활용한 프리미엄 디저트/스낵 부스입니다.", official_site: "", type: "food", tags: ["디저트", "치즈", "버터"] } },
    { id: "V03", name: "땐냥꽁냥", details: { region_name: "푸드", history: "스낵 / 디저트", features: "귀엽고 아기자기한 수제 간식이나 간단한 요깃거리를 제공하는 부스입니다.", official_site: "", type: "food", tags: ["수제간식", "가벼운안주"] } },
    { id: "V04", name: "캐리어보관소", details: { region_name: "서비스", history: "편의 시설", features: "무거운 짐이나 현장에서 구매한 병술을 안전하게 맡길 수 있는 필수 방문처입니다.", official_site: "", type: "service", tags: ["짐보관", "편의"] } },
    { id: "V06", name: "실비노", details: { region_name: "푸드", history: "안주 / 페어링", features: "와인이나 사케 등 프리미엄 주류에 곁들이기 좋은 수입 안주류(올리브, 치즈 등)를 소개합니다.", official_site: "", type: "food", tags: ["올리브", "치즈", "페어링"] } },
    { id: "V07", name: "네스상사", details: { region_name: "푸드", history: "수입 식품 / 스낵", features: "전 세계의 맛있는 스낵과 주류 페어링용 식료품을 전문으로 수입하는 기업의 부스입니다.", official_site: "", type: "food", tags: ["수입과자", "안주구매"] } },
    { id: "V08", name: "소고기초밥", details: { region_name: "푸드", history: "푸드 (식사류)", features: "즉석에서 토치로 불향을 입혀 구워내는 소고기 불초밥입니다. 든든한 식사 메뉴입니다.", official_site: "", type: "food", tags: ["불초밥", "식사"] } },
    { id: "V09", name: "꼬마루", details: { region_name: "푸드", history: "푸드 (꼬치류)", features: "축제에 절대 빠질 수 없는 닭꼬치 등 다양한 꼬치구이를 판매합니다.", official_site: "", type: "food", tags: ["꼬치구이", "안주"] } },
  ],
  U: [
    { id: "U01", name: "닛카프론티어", details: { region_name: "위스키", history: "위스키 / 스피릿", features: "닛카 위스키 산하 브랜드로 피트 향이 은은하게 감도는 클래식하고 깊은 풍미를 자랑합니다.", official_site: "", type: "whisky", tags: ["하이볼추천", "피트향", "스모키"] } },
    { id: "U04", name: "네스상사", details: { region_name: "푸드", history: "수입 식품 / 스낵", features: "U구역 관람객들이 편리하게 주류 곁들임용 스낵을 구매할 수 있도록 배치된 곳입니다.", official_site: "", type: "food", tags: ["수입스낵", "페어링"] } },
    { id: "U05", name: "소고기초밥", details: { region_name: "푸드", history: "푸드 (식사류)", features: "V08과 동일한 소고기 불초밥 부스입니다. 시음 중 든든하게 배를 채울 수 있습니다.", official_site: "", type: "food", tags: ["불초밥", "식사"] } },
    { id: "U06", name: "꼬마루", details: { region_name: "푸드", history: "푸드 (꼬치류)", features: "V09와 동일한 꼬치구이 전문 부스입니다. 위스키 하이볼과 곁들이기 완벽합니다.", official_site: "", type: "food", tags: ["꼬치구이", "감칠맛"] } },
    { id: "U07", name: "꼬알라파이", details: { region_name: "푸드", history: "푸드 (미트파이)", features: "바삭한 페이스트리 속에 육즙 가득한 고기와 소스를 채워 구워낸 호주식 미트파이 맛집입니다.", official_site: "", type: "food", tags: ["미트파이", "호주식", "묵직함"] } },
    { id: "U08", name: "케밥", details: { region_name: "푸드", history: "푸드 (식사류)", features: "즉석에서 고기를 썰어 신선한 채소와 함께 말아주는 튀르키예 전통 케밥입니다.", official_site: "", type: "food", tags: ["케밥", "터키식", "패스트푸드"] } },
    { id: "U09", name: "치즈앤모어", details: { region_name: "푸드", history: "안주 / 델리", features: "치즈를 비롯한 다양한 고급 델리 미트, 올리브 등을 다루는 부스입니다.", official_site: "", type: "food", tags: ["치즈", "델리", "마리아주"] } },
    { id: "U12", name: "에비스 맥주", details: { region_name: "맥주", history: "맥주", features: "1890년 탄생한 일본 최초의 프리미엄 맥주 브랜드입니다. 깊고 쌉싸름한 홉의 풍미가 일품입니다.", official_site: "https://www.sapporobeer.jp/yebisu", type: "beer", tags: ["프리미엄", "정통라거", "깊은맛"] } },
  ],
};

export const ALL_BOOTHS: (BoothInfo & { region: string })[] = Object.entries(FESTIVAL_BOOTHS).flatMap(
  ([region, booths]) => booths.map(b => ({ ...b, region }))
);
